### ISSUE TITLE
Android memory leak

### ISSUE THREAD

**Issue by alextkd** [paypal/PayPal-Cordova-Plugin#91] opened 2015-07-16 14:51 UTC
I noticed once the plugin is initialized it takes up to 300Mb of memory on Android 5.0.1, Galaxy S4 and even more on other devices like S6 and Nexus5 it can take up to 600Mb.

**Comment by romk1n** [comment] 2015-07-16 15:37
@alextkd can confirm what version of the plugin are using and a bit more details ? is the problem with a plugin itself or the initialization of [PayPal-Android-SDK](https://github.com/paypal/PayPal-Android-SDK) ? cc/ @braebot

**Comment by juwlee** [comment] 2015-07-16 18:09
@alextkd thank you for the offer. Please do submit a pull request, if you can. We would appreciate your contribution.

**Comment by avidas** [comment] 2015-07-17 20:32
@alextkd is that issue specific to the version of Android, 5.0.1?

**Comment by tomwhipple** [comment] 2015-07-17 20:54
@alextkd We're also wondering if you see the same problem in the example app at https://github.com/romk1n/MyCordovaShop?

**Comment by jaypatel512** [comment] 2015-09-21 19:07
Hey @alextkd ! 

We tested our sample with a large set of physical devices, and were not able to reproduce the issue that you are facing. We are closing this issue for now, as it is unreproducible. However, if you are able to reproduce this consistently, please re-open this issue, and we could try even further on getting required data to resolve this issue.

**Closed by jaypatel512** 2015-09-21 19:07 UTC
Labels: bug
