### ISSUE TITLE
iPhone 6 Plus UI Kit Crash

### ISSUE THREAD

**Issue by cihadhoruzoglu** [paypal/PayPal-Cordova-Plugin#52] opened 2015-02-09 12:04 UTC
Hi,

I tried this plugin on iPhone 4S, 5S & iPhone 6 Plus. On 4S & 5S it is work well. But on iPhone 6 Plus there is an error. I get this error when renderSinglePaymentUI works.

Console error;
![error-paypal](https://cloud.githubusercontent.com/assets/1528616/6105852/88e511b2-b064-11e4-922a-3d42dcb3e124.png)
2015-02-09 13:59:13.919 testApp[208:13303] bool _WebTryThreadLock(bool), 0x17420c390: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...
1   0x18fcaedac WebThreadLock
2   0x186e06130 <redacted>
3   0x10007e270 -[CDVViewController shouldAutorotateToInterfaceOrientation:]
4   0x10006a32c -[MainViewController shouldAutorotateToInterfaceOrientation:]
5   0x10007e38c -[CDVViewController supportedInterfaceOrientations]
6   0x186aa4d38 <redacted>
7   0x186aa48f4 <redacted>
8   0x18712226c <redacted>
9   0x186d2c900 <redacted>
10  0x186d45ba4 <redacted>
11  0x186d46e3c <redacted>
12  0x186d48d34 <redacted>
13  0x186b1e3d4 <redacted>
14  0x10006df7c __51-[PayPalMobileCordovaPlugin renderSinglePaymentUI:]_block_invoke
15  0x100868e30 _dispatch_call_block_and_release
16  0x100868df0 _dispatch_client_callout
17  0x1008759a0 _dispatch_root_queue_drain
18  0x100876f18 _dispatch_worker_thread3
19  0x1931f52e4 _pthread_wqthread
20  0x1931f4fa8 start_wqthread
(lldb) 

Error highlight In CDVViewController.m;
NSString* res = [webView stringByEvaluatingJavaScriptFromString:jsCall];

How can I fix that?

Error image attached.

**Comment by romk1n** [comment] 2015-02-09 16:19
@cihadhoruzoglu the error looks to be coming from Cordova framework itself. Can you confirm what version of the plugin, cordova version and device/simulator are you using ?

**Comment by cihadhoruzoglu** [comment] 2015-02-10 07:31
@romk1n Plugin version is 3.1.2. Cordova iOS version 3.7.0. I'm using actual iPhone 6 Plus.

I test it also on iPhone 6 and iPad Air, both of them work well.

I have not tested on simulator.

**Comment by romk1n** [comment] 2015-02-11 20:23
@cihadhoruzoglu i have tried reproducing it on iPhone 6 plus hardware and didn't observe any crashes. Can you describe exact steps and also try simulator first ? Thanks.

**Comment by cihadhoruzoglu** [comment] 2015-02-17 12:08
@romk1n I tried it on simulator and the result is same. 

I also made an another app that follows "Basic Example of the app" steps and the result is same.

 But when I download your MyCordovaShop App (https://github.com/romk1n/MyCordovaShop) it works.

I'm using Cordova 4.2.0 cli. iOS version 3.7.0.

You can download my test app https://dl.dropboxusercontent.com/u/34956307/paypalTest.zip . This is not work on iPhone 6+ but any other iOS device will be work.

**Comment by romk1n** [comment] 2015-02-23 06:43
@cihadhoruzoglu what do you mean by `iOS version 3.7.0` ?

**Comment by cihadhoruzoglu** [comment] 2015-02-23 07:41
When you type 'cordova platforms' on terminal it gives you Installed platforms & and versions.

![screen shot 2015-02-23 at 09 39 45](https://cloud.githubusercontent.com/assets/1528616/6324236/043076b4-bb40-11e4-9cad-fce95c08bbb7.png)

**Comment by romk1n** [comment] 2015-02-23 18:39
@cihadhoruzoglu i have reproduced it and released a version 3.1.3 of the plugin you can either update it through cordova repository or from [github](https://github.com/paypal/PayPal-Cordova-Plugin/releases/tag/3.1.3) directly. Let me know if that fixed the issue. Thanks!

**Comment by romk1n** [comment] 2015-02-25 19:18
I am going to close this issue, but please feel free to reopen it if the problem not resolved. Thanks!

**Closed by romk1n** 2015-02-25 19:18 UTC

**Comment by matthewborgcarr** [comment] 2018-09-02 19:01
I have a mobile app with com.paypal.cordova.mobilesdk v3.5.0

I am getting the following error when creating payment in iOS.

Please also note that the app crashes and closes immediately when not in debug mode.

`
2018-09-02 20:48:29.853486+0200 MyHurryApp[631:122102] -[NSNull length]: unrecognized selector sent to instance 0x1b69ef878
2018-09-02 20:48:29.856680+0200 MyHurryApp[631:122102] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1b69ef878'
*** First throw call stack:
(0x1843bad8c 0x1835745ec 0x1843c8098 0x1843c05c8 0x1842a641c 0x102ad75e8 0x1028c1c20 0x1033211dc 0x10332119c 0x103325d2c 0x184363070 0x184360bc8 0x184280da8 0x186266020 0x18e2a0758 0x1028beb90 0x183d11fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
`

The line causing this crash seems to be:  [PayPalMobile `preconnectWithEnvironment:environmentToUse];`

```
- (void)prepareToRender:(CDVInvokedUrlCommand *)command { [self.commandDelegate runInBackground:^{ CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK]; NSString *environment = [command.arguments objectAtIndex:0];

NSString *environmentToUse = [self parseEnvironment:environment];
if (environmentToUse) {
  // save configuration
  PayPalConfiguration *configuration = [self getPayPalConfigurationFromDictionary:[command.arguments objectAtIndex:1]];
  self.configuration = configuration;
  // do preconnect
  dispatch_async(dispatch_get_main_queue(), ^{
    [PayPalMobile preconnectWithEnvironment:environmentToUse];
  });
} else {
  pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"The provided environment is not supported"];
}

[self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}]; } 
```

In other forums I've seen suggestions that you should convert the payment amount to string, which I did however the issue is still there.

any other suggestions?
