### ISSUE TITLE
"System Error" with Paypal App installed

### ISSUE THREAD

**Issue by zpeterg** [paypal/PayPal-Cordova-Plugin#170] opened 2016-03-31 17:39 UTC
I am receiving a screen error when I try to do a cart checkout on Android: "System Error. Please try again later." Here It occurs when the PayPal app is installed on the same device. If I remove the PayPal app, the payment goes through. It works on IOS.

Here are some extracts from the log that may be helpful. I'm not certain that they are related.

------------------------------------------------------------------------------------------
W/paypal.sdk(22930): fr SN:3 PayPal Debug-ID: 1f5b4166989b0 [live, 2.14.0;release]

I/LaunchCheckinHandler(  870): Displayed io.cordova.hellocordova/com.paypal.android.sdk.payments.PaymentActivity,wp,ca,153
I/ActivityManager(  870): Displayed io.cordova.hellocordova/com.paypal.android.sdk.payments.PaymentActivity: +154ms
W/PaymentActivity(22930): Please add PayPalService.EXTRA_PAYPAL_CONFIGURATION to this activity for restart resiliency.
I/Keyboard.Facilitator(13541): onFinishInput()
I/ActivityManager(  870): START u0 {cmp=io.cordova.hellocordova/com.paypal.android.sdk.payments.PaymentMethodActivity (has extras)} from uid 10211 on display 0

W/paypal.sdk(22930): fg SN:9 PayPal Debug-ID: 81dbb9a8885ba [live, 2.14.0;release]
E/paypal.sdk(22930): request failure with http statusCode:400,exception:Bad Request
E/paypal.sdk(22930): request failed with server response:{"name":"DUPLICATE_REQUEST_ID","debug_id":"81dbb9a8885ba","message":"The value of PayPal-Request-Id header has already been used","information_link":"https://developer.paypal.com/webapps/developer/docs/api/","details":[]}
E/paypal.sdk(22930):
E/paypal.sdk(22930): DUPLICATE_REQUEST_ID

---------------------------------------------------------------------------------

I am using Android 5.1, Android SDK 22, Paypal SDK: 2.14.0, Cordova 6.0, and using Live transactions on Paypal. Here is a git of my test case that shows the error, with my credentials removed: https://github.com/zpeterg/paypal_test.git

**Comment by bluk** [comment] 2016-03-31 17:50
This may be related: https://github.com/paypal/PayPal-Android-SDK/issues/272

**Comment by bluk** [comment] 2016-03-31 18:16
Closing this one and any updates should be in https://github.com/paypal/PayPal-Android-SDK/issues/272 (thanks for the detailed logs and info).

**Closed by bluk** 2016-03-31 18:16 UTC

**Comment by zpeterg** [comment] 2016-03-31 19:09
Thanks! It's good to know that it should be resolved soon!

**Comment by ashutosh-finelogics** [comment] 2016-10-07 22:17
Is there a chance of getting resolved soon?

**Comment by bluk** [comment] 2016-10-07 22:19
@ashutosh-finelogics Please check https://github.com/paypal/PayPal-Android-SDK/issues/353 to see if that's the same issue. If it is not, can you please open a new issue with details? Thanks.

**Comment by ashutosh-finelogics** [comment] 2016-10-09 18:52
Dear @bluk  ... I dont have a paypal app installed on my app.
But, running the app created by using the plugin and following the guidelines stated , in sandbox environment.... gives the error "System Error. Please try later" after succesful login.
I am using ionic and angularjs framework for the same..

**Comment by bluk** [comment] 2016-10-10 14:58
@ashutosh-finelogics Can you please try again and open a new issue if this still occurs? If you also have any other logs, that would be very helpful. System Error is a generic error so the underlying root cause is probably different than this issue and yours.
