### ISSUE TITLE
Payment not made for 1000 or more amount

### ISSUE THREAD

**Issue by OmprakashAmarwal** [paypal/PayPal-Cordova-Plugin#211] opened 2016-09-13 07:30 UTC
Hi, I use this code for my app in ionic. But, I have a problem with the amount. I can't pay more than 999.00. If I add 1000.00 or more the payment is not made. How do I resolve this?

**Comment by bluk** [comment] 2016-09-13 15:09
If you have a `PayPal-Debug-ID` usually printed in the console logs for the error, that would help narrow down the cause. Also, I would contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com)  if this is on live production since it sounds like an account specific issue.

Closing for now since there isn't too much we can do unless more info is provided. If you have a Debug ID, then please leave a comment and we can reopen the issue.

**Closed by bluk** 2016-09-13 15:09 UTC
